version: '3.5'


services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
       - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
  adminer:
    depends_on:
      - postgres
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
    driver: local